
student_name = input("Student Name: ")
roll_no = input("Roll Number: ")
age = input("Age: ")
course = input("Course: ")
college = input("College: ")
subject_1 = float(input("Subject 1: "))
subject_2 = float(input("Subject 2: "))
subject_3 = float(input("Subject 3: "))

total_marks = (subject_1 + subject_2 + subject_3)
average = total_marks / 3

print("")
print("=" * 10, "STUDENT REPORT" + "=" * 10)
print("")
print("Name: " + student_name)
print("Roll Number: " + roll_no)
print("Age: " + age)
print("Course: " + course)
print("College: " + college)
print("")
print("subject 1: ", subject_1)
print("subject 2: ", subject_2)
print("subject 3: ", subject_3)
print("")
print("Total Marks: " + str(total_marks))
print("Average: " + str(average))
print("="*30)