# Challenge - Air Ticket Generator

name = input("Enter passenger name: ")
age = int(input("Enter age: "))
gender = input("Enter gender: ")
source = input("Enter from: ")
destination = input("Enter to: ")
flight_no = input("Enter flight number: ")
travel_date = input("Enter travel date (DD-MM-YYYY): ")
num_tickets = int(input("Enter number of tickets: "))
price = float(input("Enter price per ticket: "))

total_amount = num_tickets * price

print()
print("=" * 40)
print("AIR TICKET".center(40))
print("=" * 40)
print()
print(f"{'Passenger Name':<15}: {name}")
print(f"{'Age':<15}: {age}")
print(f"{'Gender':<15}: {gender}")
print()
print(f"{'From':<15}: {source}")
print(f"{'To':<15}: {destination}")
print(f"{'Flight Number':<15}: {flight_no}")
print(f"{'Travel Date':<15}: {travel_date}")
print()
print(f"{'Number of Tickets':<18}: {num_tickets}")
print(f"{'Price per Ticket':<18}: ₹{price:g}")
print()
print("-" * 40)
print(f"{'Total Amount':<18}: ₹{total_amount:g}")
print("-" * 40)
print()
print("HAVE A SAFE JOURNEY!".center(40))
print("=" * 40)